-- MySQL Script generated by MySQL Workbench
-- Thu Nov 19 19:16:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tcc_exemplo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcc_exemplo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc_exemplo` DEFAULT CHARACTER SET utf8 ;
USE `tcc_exemplo` ;

-- -----------------------------------------------------
-- Table `tcc_exemplo`.`tipo_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_exemplo`.`tipo_produtos` (
  `id_tipo_produtos` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo_produtos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_produtos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_exemplo`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_exemplo`.`produtos` (
  `id_produtos` INT NOT NULL AUTO_INCREMENT,
  `nome_produtos` VARCHAR(45) NOT NULL,
  `preco_produtos` REAL NOT NULL,
  `id_tipo_produtos` INT NOT NULL,
  PRIMARY KEY (`id_produtos`, `id_tipo_produtos`),
  INDEX `fk_produtos_tipo_produtos_idx` (`id_tipo_produtos` ASC),
  CONSTRAINT `fk_produtos_tipo_produtos`
    FOREIGN KEY (`id_tipo_produtos`)
    REFERENCES `tcc_exemplo`.`tipo_produtos` (`id_tipo_produtos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_exemplo`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_exemplo`.`ingredientes` (
  `id_ingredientes` INT NOT NULL AUTO_INCREMENT,
  `nome_ingredientes` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ingredientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_exemplo`.`produtos_ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_exemplo`.`produtos_ingredientes` (
  `id_produtos` INT NOT NULL,
  `id_ingredientes` INT NOT NULL,
  PRIMARY KEY (`id_produtos`, `id_ingredientes`),
  INDEX `fk_produtos_has_ingredientes_ingredientes1_idx` (`id_ingredientes` ASC),
  INDEX `fk_produtos_has_ingredientes_produtos1_idx` (`id_produtos` ASC),
  CONSTRAINT `fk_produtos_has_ingredientes_produtos1`
    FOREIGN KEY (`id_produtos`)
    REFERENCES `tcc_exemplo`.`produtos` (`id_produtos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_ingredientes_ingredientes1`
    FOREIGN KEY (`id_ingredientes`)
    REFERENCES `tcc_exemplo`.`ingredientes` (`id_ingredientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_exemplo`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_exemplo`.`pessoas` (
  `id_pessoas` INT NOT NULL AUTO_INCREMENT,
  `cpf_pessoas` VARCHAR(11) NOT NULL,
  `senha_pessoas` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_pessoas`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
